version: '3'
services:
  db:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
  redis:
    image: 'redis:6.2'
    command: redis-server --requirepass redispass
    ports:
      - '6379:6379'
  app:
    depends_on:
      - db
      - redis
    build: .
    command: bash start.sh
    ports:
      - '3000:3000'
    volumes:
      - .:/gabarito
    tty: true
    stdin_open: true
    user: '${USER_INFO}'
    links:
      - db
      - redis
    environment:
      RAILS_LOG_TO_STDOUT: 'true'
      EDITOR: 'nano'
      RAILS_ENV: 'development'
